INSERT INTO marcas (nombre, create_at, modify_at) VALUES ('Ford', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO marcas (nombre, create_at, modify_at) VALUES ('Peugeot', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO marcas (nombre, create_at, modify_at) VALUES ('Seat', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO marcas (nombre, create_at, modify_at) VALUES ('Citroen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO marcas (nombre, create_at, modify_at) VALUES ('Audi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO marcas (nombre, create_at, modify_at) VALUES ('Renault', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO extras (nombre, create_at, modify_at) VALUES ('A/C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO extras (nombre, create_at, modify_at) VALUES ('ELEVALUNAS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO extras (nombre, create_at, modify_at) VALUES ('CLIMATIZADOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO extras (nombre, create_at, modify_at) VALUES ('GPS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO coches (modelo, color, cilindrada, potencia, marca_id, create_at, modify_at) VALUES ('206', 'NEGRO', 1398, 68, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO coches (modelo, color, cilindrada, potencia, marca_id, create_at, modify_at) VALUES ('Xsara Picasso', 'GRIS', 1997, 90, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO coches (modelo, color, cilindrada, potencia, marca_id, create_at, modify_at) VALUES ('León', 'ROJO', 1498, 130, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO coches (modelo, color, cilindrada, potencia, marca_id, create_at, modify_at) VALUES ('Ibiza', 'BLANCO', 1198, 60, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO coches (modelo, color, cilindrada, potencia, marca_id, create_at, modify_at) VALUES ('C5', 'PLATEADO', 1749, 125, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO coches (modelo, color, cilindrada, potencia, marca_id, create_at, modify_at) VALUES ('Focus', 'AZUL', 1988, 110, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO coches (modelo, color, cilindrada, potencia, marca_id, create_at, modify_at) VALUES ('A4', 'PLATEADO', 1968, 122, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO coches (modelo, color, cilindrada, potencia, marca_id, create_at, modify_at) VALUES ('A6', 'AZUL', 2995, 340, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO coches (modelo, color, cilindrada, potencia, marca_id, create_at, modify_at) VALUES ('Twingo', 'AMARILLO', 1149, 75, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO coches (modelo, color, cilindrada, potencia, marca_id, create_at, modify_at) VALUES ('Megane', 'BLANCO', 1749, 150, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (18000, '2022-08-01', '2023-07-31', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (22595, '2022-10-07', '2023-03-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (21000, '2022-02-01', '2023-05-12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (9999, '2022-02-01', '2023-11-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (24495, '2022-09-20', '2023-04-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (32995, '2021-12-01', '2023-12-31', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (17845, '2023-01-01', '2023-04-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (27799, '2022-10-01', '2023-04-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (24385, '2022-07-01', '2023-10-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (20385, '2022-03-01', '2023-05-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO precios (cantidad, fecha_inicio, fecha_fin, create_at, modify_at) VALUES (19385, '2022-03-01', '2023-05-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO coches_precios (coche_id, precios_id) VALUES (1, 1);
INSERT INTO coches_precios (coche_id, precios_id) VALUES (2, 10);
INSERT INTO coches_precios (coche_id, precios_id) VALUES (3, 2);
INSERT INTO coches_precios (coche_id, precios_id) VALUES (4, 9);
INSERT INTO coches_precios (coche_id, precios_id) VALUES (5, 3);
INSERT INTO coches_precios (coche_id, precios_id) VALUES (6, 8);
INSERT INTO coches_precios (coche_id, precios_id) VALUES (7, 4);
INSERT INTO coches_precios (coche_id, precios_id) VALUES (8, 7);
INSERT INTO coches_precios (coche_id, precios_id) VALUES (9, 5);
INSERT INTO coches_precios (coche_id, precios_id) VALUES (10, 6);
INSERT INTO coches_precios (coche_id, precios_id) VALUES (1, 11);

INSERT INTO coches_extras (coche_id, extras_id) VALUES (1, 1);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (1, 2);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (2, 1);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (2, 2);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (3, 3);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (3, 2);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (4, 1);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (4, 2);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (5, 2);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (5, 3);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (6, 1);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (6, 2);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (7, 2);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (7, 3);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (7, 4);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (8, 2);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (8, 3);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (8, 4);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (9, 1);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (9, 2);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (10, 2);
INSERT INTO coches_extras (coche_id, extras_id) VALUES (10, 3);
